# Generated by Django 5.0.4 on 2024-04-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_datasabertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasabertas',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
