# Generated by Django 5.0.4 on 2024-04-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_datasabertas_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasabertas',
            name='descricao',
        ),
    ]
